appconf:
  provider: gwhttpconf
  section: gwconf
gwconf:
  addr: "https://configsvr.oceanho.com"
  appid: ""
  secret: ""
  type: plaintext
  provider: defaultHttpProvider
  decryptor:
    algs: plugins/security/configsvr/lh-conf-manger.so
    args:
      - --salt Salt$#NB
localfs:
  path: "/etc/gw/all.yaml"
  type: plaintext
  provider: defaultHttpProvider
  decryptor:
    algs: plugins/security/configsvr/lh-conf-manger.so
    args:
      - --salt Salt$#NB
