configsvr:
  addr: "https://configsvr.oceanho.com"
  appid: ""
  secret: ""
  type: plaintext
  provider: defaultHttpProvider
  decryptor:
    algs: plugins/security/configsvr/lh-conf-manger.so
    args:
      - --salt Salt$#NB
