api:
  prefix: "api/v1"
  version: "Version 1.0"
  remarks: "User Account Platform API Services."
  security:
    auth:
      disable: False
    allow-urls:
      - POST:${API_PREFIX}/ucp/account/login
common:
  backend:
    db:
    - name: primary
      dirver: mysql
      addr: 127.0.0.1
      port: 3306
      user: root
      password: oceanho
      database: djdb
      ssl_mode: on
      ssl_cert: ap
      args:
        charset: utf8
        parseTime: True
    cache:
    - name: primary
      addr: 127.0.0.1
      port: 6379
      type: redis
      auth:
        disable: True
        user: ocean
        database: 1
        password: oceanho
