// Code generated by "stringer -type=ArtifactCategory,StorageEngine"; DO NOT EDIT.

package Db

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[GzipFile-0]
	_ = x[GenericFile-1]
	_ = x[DockerImage-2]
}

const _ArtifactCategory_name = "GzipFileGenericFileDockerImage"

var _ArtifactCategory_index = [...]uint8{0, 8, 19, 30}

func (i ArtifactCategory) String() string {
	if i >= ArtifactCategory(len(_ArtifactCategory_index)-1) {
		return "ArtifactCategory(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ArtifactCategory_name[_ArtifactCategory_index[i]:_ArtifactCategory_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StorageEngineDocker-1]
	_ = x[StorageEngineFileSystem-2]
}

const _StorageEngine_name = "StorageEngineDockerStorageEngineFileSystem"

var _StorageEngine_index = [...]uint8{0, 19, 42}

func (i StorageEngine) String() string {
	i -= 1
	if i >= StorageEngine(len(_StorageEngine_index)-1) {
		return "StorageEngine(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _StorageEngine_name[_StorageEngine_index[i]:_StorageEngine_index[i+1]]
}
