service:
  name: "My App"
  prefix: "/api/v1"
  version: "Version 1.0"
  remarks: "User Account Platform  Services."
  security:
    crypto:
      hash:
        alg: "sha256" # md5 / sha1 / sha256
        salt: "cvMC33eY7o9YKarcUr7VCf9XLFmHXKWJ"
      protect:
        alg: "aes"  # aes / 3des / rsa
        secret: "sPJF7yVnCvgctCJJ9scdTjwqzeenKnHH"
      cert:
        privateKey: "config/etc/gw.key"
        publicKey: "config/etc/gw.pem"
        isFile: True # true/false. The key,cert can be base64 string or A file path.
    timeout:  # Timeout control, units is millisecond
      redis: 1000
      database: 2000
      mongo: 2000
      http: 2000
    auth:
      trustSidKey: "x-gw-trust-sid" # 如果配置这项，请务必确保您发送到后端节点的 http header -> <trustSidKey> 是可信的.
      paramKey:
        passport: "email"
        secret: "password"
        verifyCode: "verifyCode"
      paramPattern:
        passport: '^\S{5,64}$'
        secret: '^\S{5,64}$'
        verifyCode: '^[0-9]{0,8}$'
      session:
        defaultStore:
          name: primary
          prefix: gw-sid
      cookie:
        key: "_gid"
        domain: ""  # xxx.com / xxx.net
        path: "/"
        maxAge: 7200
        httpOnly: False
        secure: False
      disable: False
      authServer: https://auth.gw-framework.com
      loginUrl: ${PREFIX}/gw/auth/login
      logoutUrl: ${PREFIX}/gw/auth/logout
      allowUrls:
      - name: auth
        urls:
        - POST:${PREFIX}/ucp/account/login
        - POST:${PREFIX}/ucp/account/login
        ips:
        - 127.0.0.1/32
        - 192.168.0.0/24
    queryLimit:
      minPageSize: 20
      maxPageSize: 2000
  services:
    plugin: "/apps/dylib/s/*.so"

common:
  backend:
    db:
    - name: primary
      driver: mysql
      addr: 127.0.0.1
      port: 3306
      user: gw
      password: gw@123
      database: gwdb
      ssl_mode: on
      ssl_cert: ap
      args:
        charset: utf8
        parseTime: True
    cache:
    - name: primary
      driver: redis
      addr: 127.0.0.1
      port: 6379
      type: redis
      auth:
        disable: True
        user: ocean
        database: 1
        password: oceanho

# Any Your custom configuration item at here.
# More: https://github.com/oceanho/gw/master/docs/configuration#custom
custom:
#  user: OceanHo
#  tags:
#    - body
#    - programmer
